package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"

	"aliasly/internal/config"
)

// initCmd represents the init command.
// It outputs shell code that creates aliases for all configured aliases.
var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Output shell integration code",
	Long: `Output shell code that creates aliases for all your configured aliases.

Add this to your shell config file (.bashrc, .zshrc, etc.):

  eval "$(al init)"

After that, you can use your aliases directly without the 'al' prefix:

  gs              # instead of: al gs
  gc "message"    # instead of: al gc "message"

The 'al' command is still used for management:

  al add          # Add new alias
  al remove       # Remove alias
  al config       # Open web UI
  al list         # List aliases`,

	Run: runInitCmd,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInitCmd(cmd *cobra.Command, args []string) {
	// Get all aliases
	aliases, err := config.GetAllAliases()
	if err != nil {
		fmt.Fprintf(os.Stderr, "# Error loading aliases: %v\n", err)
		return
	}

	// Get the path to the al binary
	alPath, err := os.Executable()
	if err != nil {
		alPath = "al" // Fallback to assuming it's in PATH
	}

	// Detect shell type
	shell := os.Getenv("SHELL")
	isZsh := contains(shell, "zsh")
	isFish := contains(shell, "fish")

	// Output shell code
	fmt.Println("# Aliasly shell integration")
	fmt.Println("# Generated by: al init")
	fmt.Println()

	if isFish {
		// Fish shell syntax
		for _, alias := range aliases {
			fmt.Printf("# %s\n", alias.Description)
			fmt.Printf("function %s; \"%s\" \"%s\" $argv; end\n", alias.Name, alPath, alias.Name)
		}
	} else if isZsh {
		// Zsh syntax - use functions for reliability
		for _, alias := range aliases {
			fmt.Printf("# %s\n", alias.Description)
			fmt.Printf("function %s { \"%s\" \"%s\" \"$@\" }\n", alias.Name, alPath, alias.Name)
		}
	} else {
		// Bash syntax - use functions for reliability
		for _, alias := range aliases {
			fmt.Printf("# %s\n", alias.Description)
			fmt.Printf("%s() { \"%s\" \"%s\" \"$@\"; }\n", alias.Name, alPath, alias.Name)
		}
	}

	fmt.Println()
	fmt.Println("# Aliasly integration loaded")
}

// GetShellConfigFile returns the path to the user's shell config file.
func GetShellConfigFile() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}

	// Check which shell is being used
	shell := os.Getenv("SHELL")

	switch {
	case contains(shell, "zsh"):
		return filepath.Join(home, ".zshrc")
	case contains(shell, "bash"):
		// On macOS, bash uses .bash_profile for login shells
		if runtime.GOOS == "darwin" {
			bashProfile := filepath.Join(home, ".bash_profile")
			if _, err := os.Stat(bashProfile); err == nil {
				return bashProfile
			}
		}
		return filepath.Join(home, ".bashrc")
	case contains(shell, "fish"):
		return filepath.Join(home, ".config", "fish", "config.fish")
	default:
		// Default to .bashrc
		return filepath.Join(home, ".bashrc")
	}
}

func contains(s, substr string) bool {
	return len(s) >= len(substr) && (s == substr || len(s) > 0 && containsAt(s, substr))
}

func containsAt(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
